#add for oracle
# export ORACLE_BASE=/home/suzhen/oracle
# export ORACLE_HOME=$ORACLE_BASE/product/1120
# export ORACLE_SID=test1
# export ORACLE_TERM=xterm
# export LD_ASSUME_KERNEL=2.6.18
# export NLS_LANG=AMERICAN_america.zhs16gbk
# export ORA_NLS33=$ORACLE_HOME/ocommon/nls/admin/data
# export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib:/usr/local/lib
# export PATH=$ORACLE_HOME/bin:$ORA_CRS_HOME/bin:$PATH
